---
kind: pipeline
name: "Build smqtk for python 3.7"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 3.7"
    image: python:3.7
    commands:
      - git clean -xdf
      - apt-get update && apt-get -y install cmake
      - pip3 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - cmake -DSMQTK_BUILD_FLANN=OFF .. 
      - make -j$(nproc)
      - cd ..
      - . build/setup_env.build.sh
      - python3 setup.py test

trigger: 
  event:
    - pull_request

---
kind: pipeline
name: "Build smqtk for python 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 3.6"
    image: python:3.6
    commands:
      - git clean -xdf
      - apt-get update && apt-get -y install cmake
      - pip3 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - cmake -DSMQTK_BUILD_FLANN=OFF .. 
      - make -j$(nproc)
      - cd ..
      - . build/setup_env.build.sh
      - python3 setup.py test

trigger: 
  event:
    - pull_request

---
kind: pipeline
name: "Build smqtk for python 2.7"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Build smqtk python 2.7"
    image: python:2.7
    commands:
      - git clean -xdf
      - apt-get update  && apt-get -y install cmake
      - pip2 install -r requirements.txt -r requirements.test.txt
      - mkdir build
      - cd build
      - cmake -DSMQTK_BUILD_FLANN=OFF ..
      - make -j$(nproc)
      - cd ..
      - . build/setup_env.build.sh
      - python2 setup.py test
      
trigger: 
  event:
    - pull_request
