version: '3'
services:
  postgres:
    image: postgres
    container_name: smqtk-postgres

  smqtk:
    build: ./smqtk_services_2
    links:
      - postgres
    volumes:
      - "${IMAGE_DIR}:/data"
      - './smqtk_logs:/logs'
    command: "-b"

  wrapper:
    build: ./smqtk_wrapper_python
    links:
      - smqtk
    volumes:
      - "${IMAGE_DIR}:/data"
      - './newdata:/newdata'
      - './links:/links'
    ports:
      - '12345:12345'
      - '12346:12346'
